# Generated by Django 5.2.12 on 2026-03-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0002_alter_user_managers_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
