# Generated by Django 5.2.12 on 2026-03-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyflow', '0004_alter_user_managers_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
